### ISSUE TITLE
DevTunnel not getting picked up. DevTunnelNotPublicError even after creating a new tunnel

### ISSUE THREAD

**Issue by praskutti** [OfficeDev/teams-toolkit#11136]
I downloaded and installed Teams Toolkit for Visual Studio 2022 (Professional and Community) 17.9.4. When I created a new project (Echo Bot template), I followed the instructions as per GetStarted.md file. 

I created a Dev Tunnel as suggested in step 1. But when I clicked on "Prepare App for Dependencies", the get hit with "The DevTunnel '' is not set to public". But I can confirm and assure that the default DevTunnel is in fact public. Is there any documentation on how to resolve this? Why is the DevTunnel not printed in the error message?

I am using VS2022 behind a corporate VPN. 

When I choose "none" as the DevTunnel, I then get a "Cannot send API call to dev.teams.microsoft.com" error. I am not able to proceed any further. 

Can someone please help?

Visual Studio 2022 (Professional and Community) 17.9.4
Windows 11
NodeJS 18.7.1

Edit 1: This is the exact error I am getting : [Visual Studio - Teams Project Issue](https://stackoverflow.com/questions/78168554/visual-studio-teams-project-issue)
Copying the error message, so it is searchable in here:
```"The dev tunnel with the name '' is not set to public access. Please use a public dev tunnel in the debug dropdown menu (Dev Tunnels) to prepare Teams app."```

Edit 2 : If I use "none" as the DevTunnel, I get this error : [Prepare Teams App Dependencies fails behind proxy](https://stackoverflow.com/questions/75106076/prepare-teams-app-dependencies-fails-behind-proxy)
Copying the error message, so it is searchable in here:
```I create a new Teams application in Visual Studio 2022 (17.4.4). When I try the "Prepare Teams App Dependencies", I get a failure from AppStudioPlugin with the message "API call to Developer Portal failed: Error, connect EACCES 52.113.194.132:443, API name: create-app, ..." I am behind a proxy, and I see a drop in the firewall logs to 52.113.194.132:443, so it's not going to the proxy.```

I tried using "Private", "Organization" and "Public" as access level, used GitHub Enterprise account as well as corporate M365 account, but same errors

**Comment by praskutti** [comment]
HI Tian,  yes, it is set to public (if you see my original post, I mentioned that I tried all the combinations).

Regards
Prasanna Govindaraju
4252838225
________________________________

**Comment by aurnor** [comment]
Exact same issue here. The Dev Tunnel is set as public and I also get the DevTunnelNotPublicError.

**Comment by praskutti** [comment]
@xiaolang124 , do you mean the calls going out of Visual Studio or after the teams app is running after hitting the F5 button?

Also, the name of the devtunnel is not printed in the error message. It is printed as " ". Does it mean the Echo Bot template is not utilising the tunnels at all?

**Comment by praskutti** [comment]
To add, I am able to run / debug an app using the default templates from Visual Studio Code. Only Visual Studio 2022 is where I am unable to run or prepare app.

**Comment by praskutti** [comment]
@xiaolang124  , can you please let us know what the bug was?

**Comment by brianemmettjnr** [comment]
Just to say, I came across this error and figured out that Visual Studio was running teams toolkit via Node on the backend, and because I'm behind a corporate proxy this was failing due to non matching certificates. Setting NODE_TLS_REJECT_UNAUTHORIZED=0 in the environment I launched VS fixed this for me, and I've not had to set it since.

**Comment by adashen** [comment]
Thanks for the information close the bug as the issue is resolved.

**Comment by praskutti** [comment]
@adashen , that suggested solution (NODE_TLS_REJECT_UNAUTHORIZED=0) did not work for me. Can you please re-open this? I am still hit with DevTunnelNotPublicError even though I chose a tunnel that is public. The error message also does not log the name of the tunnel (comes out as blank). 

@brianemmettjnr , did you add it as an environment variable? Where did you set this value exactly? Can you please walk me through?

**Comment by freyfrey01** [comment]
@xiaolang124 what is the status on this? I am still encountering the same issue with a work account to create a dev tunnel.

![Image](https://github.com/user-attachments/assets/71ea0478-f44d-4267-b63d-76ed19d5baf0)

![Image](https://github.com/user-attachments/assets/03845db3-aac9-4cc1-884b-46059be1a855)

{
  "errorType": "UserError",
  "source": "Fx-VS",
  "name": "DevTunnelNotPublicError",
  "message": "The dev tunnel with the name '' is not set to public access. Please use a public dev tunnel in the debug dropdown menu (Dev Tunnels) to prepare Teams app.",
  "stack": null,
  "innerError": null,
  "userData": null,
  "timestamp": "2025-03-19T12:42:10.3682925-05:00",
  "displayMessage": "The dev tunnel with the name '' is not set to public access. Please use a public dev tunnel in the debug dropdown menu (Dev Tunnels) to prepare Teams app.",
  "helpLink": null,
  "issueLink": null
}
