### ISSUE TITLE
bug report: AppStudioPlugin.TeamsAppUpdateFailed

### ISSUE THREAD

**Issue by masamori0083** [OfficeDev/teams-toolkit#11935]
Unable to update Teams app with ID 4407f4cf-3272-42fc-ac40-a5efc8769da8 in Teams Developer Portal due to Unable to make API call to Developer Portal: AxiosError, Request failed with status code 422, API name: create-app, X-Correlation-ID: 60037e5a-ad8c-4fab-859d-cb0e67573930. This may be due to a temporary service error. Try again after a few minutes. data: "Error while updating assets to the blob storage for tenant id 912c4516-e818-4af0-bda4-53123f40d4bf, appDefinitionId 4407f4cf-3272-42fc-ac40-a5efc8769da8. Error message: Error while deleting assets from the blob storage for tenant id 912c4516-e818-4af0-bda4-53123f40d4bf, appDefinitionId 4407f4cf-3272-42fc-ac40-a5efc8769da8. Error message: This request is not authorized to perform this operation.\nRequestId:40d83e6c-c01e-0035-0b18-c7069e000000\nTime:2024-06-25T16:01:45.2578976Z\r\nStatus: 403 (This request is not authorized to perform this operation.)\r\nErrorCode: AuthorizationFailure\r\n\r\nContent:\r\n﻿<%3Fxml version=\"1.0\" encoding=\"utf-8\"%3F><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:40d83e6c-c01e-0035-0b18-c7069e000000\nTime:2024-06-25T16:01:45.2578976Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 40d83e6c-c01e-0035-0b18-c7069e000000\r\nx-ms-client-request-id: 66a35f4a-5c9d-40bd-919f-1b5ce9ce4cc1\r\nx-ms-version: 2024-05-04\r\nx-ms-error-code: AuthorizationFailure\r\nDate: Tue, 25 Jun 2024 16:01:44 GMT\r\nContent-Length: 246\r\nContent-Type: application/xml\r\n" Alternatively, you can skip this step by choosing the 'Debug in Test Tool' option.

stack:
TeamsAppUpdateFailed: Unable to update Teams app with ID 4407f4cf-3272-42fc-ac40-a5efc8769da8 in Teams Developer Portal due to Unable to make API call to Developer Portal: AxiosError, Request failed with status code 422, API name: create-app, X-Correlation-ID: 60037e5a-ad8c-4fab-859d-cb0e67573930. This may be due to a temporary service error. Try again after a few minutes. data: "Error while updating assets to the blob storage for tenant id 912c4516-e818-4af0-bda4-53123f40d4bf, appDefinitionId 4407f4cf-3272-42fc-ac40-a5efc8769da8. Error message: Error while deleting assets from the blob storage for tenant id 912c4516-e818-4af0-bda4-53123f40d4bf, appDefinitionId 4407f4cf-3272-42fc-ac40-a5efc8769da8. Error message: This request is not authorized to perform this operation.\nRequestId:40d83e6c-c01e-0035-0b18-c7069e000000\nTime:2024-06-25T16:01:45.2578976Z\r\nStatus: 403 (This request is not authorized to perform this operation.)\r\nErrorCode: AuthorizationFailure\r\n\r\nContent:\r\n﻿<%3Fxml version=\"1.0\" encoding=\"utf-8\"%3F><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:40d83e6c-c01e-0035-0b18-c7069e000000\nTime:2024-06-25T16:01:45.2578976Z</Message></Error>\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 40d83e6c-c01e-0035-0b18-c7069e000000\r\nx-ms-client-request-id: 66a35f4a-5c9d-40bd-919f-1b5ce9ce4cc1\r\nx-ms-version: 2024-05-04\r\nx-ms-error-code: AuthorizationFailure\r\nDate: Tue, 25 Jun 2024 16:01:44 GMT\r\nContent-Length: 246\r\nContent-Type: application/xml\r\n"
    at Function.SystemError (<REDACTED: user-file-path>/extension.js:2:610777)
    at ConfigureTeamsAppDriver.update (<REDACTED: user-file-path>/extension.js:2:562630)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConfigureTeamsAppDriver.<anonymous> (<REDACTED: user-file-path>/extension.js:2:492921)
    at ConfigureTeamsAppDriver.execute (<REDACTED: user-file-path>/extension.js:2:560214)
    at Lifecycle.executeImpl (<REDACTED: user-file-path>/extension.js:2:232111)
    at Lifecycle.execute (<REDACTED: user-file-path>/extension.js:2:229268)
    at Coordinator.provision (<REDACTED: user-file-path>/extension.js:2:272865)
    at Coordinator.<anonymous> (<REDACTED: user-file-path>/extension.js:2:1045956)
    at FxCore.provisionResources (<REDACTED: user-file-path>/extension.js:2:964918)
    at FxCore.exports.EnvWriterMW (<REDACTED: user-file-path>/extension.js:2:871186)
    at FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path>/extension.js:2:1049708)
    at FxCore.exports.ConcurrentLockerMW (<REDACTED: user-file-path>/extension.js:2:1048659)
    at envLoaderMWImpl (<REDACTED: user-file-path>/extension.js:2:871066)
    at FxCore.<anonymous> (<REDACTED: user-file-path>/extension.js:2:869964)
    at FxCore.exports.ProjectMigratorMWV3 (<REDACTED: user-file-path>/extension.js:2:1080366)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>/extension.js:2:1050205)
    at FxCore.<anonymous> (<REDACTED: user-file-path>/extension.js:2:1045956)

**Comment by anchenyi** [comment]
hi @masamori0083, this error comes from an internal dependency service. I have contacted the related team and will update here ASAP. Thanks.

**Comment by alexChiu127** [comment]
We encountered the same issue, please fix it as soon as possible.

**Comment by anchenyi** [comment]
hi @masamori0083, could you provide the app package you are using for further investigation?

**Comment by masamori0083** [comment]
Thanks for your reply, and I uploaded app package. Is it enough for you?
By the way, until yesterday, the other teams app template worked well, however, it doesn't suddenly today.
[meeting-sum-card.zip](https://github.com/user-attachments/files/16065877/meeting-sum-card.zip)

**Comment by anchenyi** [comment]
hi @masamori0083, I tried the zip package you provided, but I couldn't reproduce the error, and the "provision" succeeded. Could you try again to see if the error still exists? Thanks.

**Comment by anchenyi** [comment]
Update: The issue with our dependency service has been fixed. Please retry. Sorry for the inconvenience.

**Comment by masamori0083** [comment]
@anchenyi 
Thanks for your cooperation!
I could deploy it in local env.

**Comment by greigs** [comment]
@anchenyi is the same problem happening again? See the most recent issues.

**Comment by anchenyi** [comment]
hi @greigs, the recent issues were due to a different reason, and they have been resolved. Sorry for the inconvenience.

**Comment by anandrathnas** [comment]
https://github.com/OfficeDev/teams-toolkit/issues/12403 still an issue

**Comment by jayzhang** [comment]
The issue of #12403 seems to have different cause from what of this issue. We will keep tracking it in the new issue #12403.
